Feb 22 18:43:45 cloud-init[2665]: util.py[DEBUG]: Cloud-init v. 18.2-72.amzn2.0.6 running 'init-local' at Fri, 22 Feb 2019 18:43:45 +0000. Up 5.10 seconds.
Feb 22 18:43:45 cloud-init[2665]: main.py[DEBUG]: No kernel command line url found.
Feb 22 18:43:45 cloud-init[2665]: main.py[DEBUG]: Closing stdin.
Feb 22 18:43:45 cloud-init[2665]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
Feb 22 18:43:45 cloud-init[2665]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
Feb 22 18:43:45 cloud-init[2665]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
Feb 22 18:43:45 cloud-init[2665]: handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
Feb 22 18:43:45 cloud-init[2665]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Feb 22 18:43:45 cloud-init[2665]: stages.py[DEBUG]: no cache found
Feb 22 18:43:45 cloud-init[2665]: handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
Feb 22 18:43:45 cloud-init[2665]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Feb 22 18:43:45 cloud-init[2665]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Feb 22 18:43:45 cloud-init[2665]: __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', u'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
Feb 22 18:43:45 cloud-init[2665]: __init__.py[DEBUG]: Searching for local data source in: []
Feb 22 18:43:45 cloud-init[2665]: main.py[DEBUG]: No local datasource found
Feb 22 18:43:45 cloud-init[2665]: stages.py[DEBUG]: network config disabled by system_cfg
Feb 22 18:43:45 cloud-init[2665]: stages.py[INFO]: network config is disabled by system_cfg
Feb 22 18:43:45 cloud-init[2665]: main.py[DEBUG]: [local] Exiting without datasource in local mode
Feb 22 18:43:45 cloud-init[2665]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Feb 22 18:43:45 cloud-init[2665]: util.py[DEBUG]: Read 10 bytes from /proc/uptime
Feb 22 18:43:45 cloud-init[2665]: util.py[DEBUG]: cloud-init mode 'init' took 0.063 seconds (0.06)
Feb 22 18:43:45 cloud-init[2665]: handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
Feb 22 18:43:47 cloud-init[3058]: util.py[DEBUG]: Cloud-init v. 18.2-72.amzn2.0.6 running 'init' at Fri, 22 Feb 2019 18:43:47 +0000. Up 7.82 seconds.
Feb 22 18:43:47 cloud-init[3058]: main.py[DEBUG]: No kernel command line url found.
Feb 22 18:43:47 cloud-init[3058]: main.py[DEBUG]: Closing stdin.
Feb 22 18:43:47 cloud-init[3058]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
Feb 22 18:43:47 cloud-init[3058]: util.py[DEBUG]: Running command ['ip', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:47 cloud-init[3058]: util.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:47 cloud-init[3058]: util.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3058]: main.py[DEBUG]: Checking to see if files that we need already exist from a previous run that would allow us to stop early.
Feb 22 18:43:48 cloud-init[3058]: main.py[DEBUG]: Execution continuing, no previous run detected that would allow us to stop early.
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: no cache found
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', u'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: Searching for network data source in: [u'DataSourceEc2', u'DataSourceNone']
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 37 bytes from /sys/hypervisor/uuid
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 1298 bytes from /proc/self/status
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /sys/class/dmi/id/product_serial (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 37 bytes from /sys/class/dmi/id/product_serial
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: dmi data /sys/class/dmi/id/product_serial returned ec2fd50f-ee3b-b593-7bcd-4f8c232ad7b4
Feb 22 18:43:48 cloud-init[3058]: DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_platform=AWS
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Resolving URL: http://169.254.169.254 took 0.041 seconds
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Resolving URL: http://instance-data.:8773 took 0.004 seconds
Feb 22 18:43:48 cloud-init[3058]: DataSourceEc2.py[DEBUG]: Removed the following from metadata urls: ['http://instance-data.:8773']
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/2009-04-04/meta-data/instance-id' with {'url': 'http://169.254.169.254/2009-04-04/meta-data/instance-id', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 50.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2009-04-04/meta-data/instance-id (200, 19b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254'
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/2016-09-02/meta-data/instance-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-id', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET'} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-id (200, 19b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: DataSourceEc2.py[DEBUG]: Found preferred metadata version 2016-09-02
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/user-data' with {'url': 'http://169.254.169.254/2016-09-02/user-data', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ (200, 263b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/ami (200, 9b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/metrics/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/metrics/', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/metrics/ (200, 7b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/ (200, 11b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/ (200, 5b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/ (200, 230b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/ipv4-associations/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/ipv4-associations/', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/ipv4-associations/ (200, 12b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/ipv4-associations/3.95.202.121' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/ipv4-associations/3.95.202.121', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/ipv4-associations/3.95.202.121 (200, 12b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/local-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/local-hostname', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/local-hostname (200, 28b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/security-groups' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/security-groups', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/security-groups (200, 15b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/public-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/public-hostname', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/public-hostname (200, 40b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/vpc-ipv4-cidr-blocks', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/subnet-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/subnet-id', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/subnet-id (200, 15b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/public-ipv4s' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/public-ipv4s', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/public-ipv4s (200, 12b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/interface-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/interface-id', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/interface-id (200, 21b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/mac' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/mac', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/mac (200, 17b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/security-group-ids' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/security-group-ids', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/security-group-ids (200, 20b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/vpc-ipv4-cidr-block', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/local-ipv4s' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/local-ipv4s', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/local-ipv4s (200, 12b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/owner-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/owner-id', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/owner-id (200, 12b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/subnet-ipv4-cidr-block', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/subnet-ipv4-cidr-block (200, 14b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/device-number' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/device-number', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/device-number (200, 1b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/vpc-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/vpc-id', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/network/interfaces/macs/12:8b:bd:c6:0e:8c/vpc-id (200, 12b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/placement/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/placement/', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/placement/ (200, 17b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/placement/availability-zone (200, 10b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-keys/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-keys/', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-keys/ (200, 8b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-keys/0/openssh-key (200, 388b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/ (200, 16b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/domain' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/domain', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/domain (200, 13b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/services/partition' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/services/partition', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/services/partition (200, 3b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/profile' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/profile', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/profile (200, 11b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/local-ipv4' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/local-ipv4', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/local-ipv4 (200, 12b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/reservation-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/reservation-id', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/reservation-id (200, 19b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/local-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/local-hostname', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/local-hostname (200, 28b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/security-groups' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/security-groups', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/security-groups (200, 15b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-launch-index', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-launch-index (200, 1b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-hostname', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-hostname (200, 40b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/hostname' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/hostname', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/hostname (200, 28b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-id', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-id (200, 21b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-action' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-action', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-action (200, 4b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/mac' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/mac', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/mac (200, 17b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/public-ipv4' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/public-ipv4', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/public-ipv4 (200, 12b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/ami-manifest-path (200, 9b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-type' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-type', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-type (200, 8b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/meta-data/instance-id' with {'url': 'http://169.254.169.254/2016-09-02/meta-data/instance-id', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/meta-data/instance-id (200, 19b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity (200, 33b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/document', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/document (200, 476b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/rsa2048 (200, 1434b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/pkcs7 (200, 1118b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature', 'headers': {'User-Agent': 'Cloud-Init/18.2-72.amzn2.0.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Feb 22 18:43:48 cloud-init[3058]: url_helper.py[DEBUG]: Read from http://169.254.169.254/2016-09-02/dynamic/instance-identity/signature (200, 174b) after 1 attempts
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
Feb 22 18:43:48 cloud-init[3058]: stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 1585 bytes from /etc/cloud/cloud.cfg
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Attempting to load yaml from string of length 1585 with allowed root types (<type 'dict'>,)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 590 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Attempting to load yaml from string of length 590 with allowed root types (<type 'dict'>,)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 2106 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Attempting to load yaml from string of length 2106 with allowed root types (<type 'dict'>,)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: loaded blob returned None, returning default.
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-01810bd6547e312e1'
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-01810bd6547e312e1/datasource (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/datasource - wb: [644] 29 bytes
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 8244 bytes
Feb 22 18:43:48 cloud-init[3058]: main.py[DEBUG]: [net] init will now be targeting instance id: i-01810bd6547e312e1. new=True
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 1585 bytes from /etc/cloud/cloud.cfg
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Attempting to load yaml from string of length 1585 with allowed root types (<type 'dict'>,)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 590 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Attempting to load yaml from string of length 590 with allowed root types (<type 'dict'>,)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 2106 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Attempting to load yaml from string of length 2106 with allowed root types (<type 'dict'>,)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: loaded blob returned None, returning default.
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: Stable ifnames disabled by net.ifnames=0 in /proc/cmdline
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /sys/class/net/eth0/carrier (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/carrier
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: network config disabled by system_cfg
Feb 22 18:43:48 cloud-init[3058]: stages.py[INFO]: network config is disabled by system_cfg
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/user-data.txt - wb: [600] 0 bytes
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/user-data.txt.i - wb: [600] 345 bytes
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/vendor-data.txt - wb: [600] 0 bytes
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/vendor-data.txt.i - wb: [600] 345 bytes
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Feb 22 18:43:48 cloud-init[3058]: cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-92-21.ec2.internal (ip-172-31-92-21)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-92-21.ec2.internal'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-92-21.ec2.internal
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Running command ['hostname', 'ip-172-31-92-21.ec2.internal'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/consume_data - wb: [644] 20 bytes
Feb 22 18:43:48 cloud-init[3058]: helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/consume_data'>)
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
Feb 22 18:43:48 cloud-init[3058]: launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Added default handler for set(['text/cloud-config-jsonp', 'text/cloud-config']) from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Added default handler for set(['text/x-shellscript']) from ShellScriptPartHandler: [['text/x-shellscript']]
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Added default handler for set(['text/cloud-boothook']) from BootHookPartHandler: [['text/cloud-boothook']]
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Added default handler for set(['text/upstart-job']) from UpstartJobPartHandler: [['text/upstart-job']]
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__begin__, None, 2) with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: {'Content-Type': 'text/x-not-multipart', 'Content-Disposition': 'attachment; filename="part-001"', 'MIME-Version': '1.0'}
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: Empty payload of type text/x-not-multipart
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__end__, None, 2) with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/cloud-config.txt - wb: [600] 0 bytes
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: no vendordata from datasource
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 1585 bytes from /etc/cloud/cloud.cfg
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Attempting to load yaml from string of length 1585 with allowed root types (<type 'dict'>,)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 590 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Attempting to load yaml from string of length 590 with allowed root types (<type 'dict'>,)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 2106 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Attempting to load yaml from string of length 2106 with allowed root types (<type 'dict'>,)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: loaded blob returned None, returning default.
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: loaded blob returned None, returning default.
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: loaded blob returned None, returning default.
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 7073 bytes
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
Feb 22 18:43:48 cloud-init[3058]: main.py[DEBUG]: no di_report found in config.
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_migrator.pyc'>) with frequency always
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
Feb 22 18:43:48 cloud-init[3058]: helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f71994142d0>)
Feb 22 18:43:48 cloud-init[3058]: cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_bootcmd.pyc'>) with frequency always
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
Feb 22 18:43:48 cloud-init[3058]: helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f7199414390>)
Feb 22 18:43:48 cloud-init[3058]: cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_write_files.pyc'>) with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_write_files - wb: [644] 20 bytes
Feb 22 18:43:48 cloud-init[3058]: helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_write_files'>)
Feb 22 18:43:48 cloud-init[3058]: cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_write_metadata.pyc'>) with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_write_metadata - wb: [644] 20 bytes
Feb 22 18:43:48 cloud-init[3058]: helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_write_metadata'>)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /etc/yum/vars/awsregion - wb: [644] 9 bytes
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsregion to 0:0
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /etc/yum/vars/awsdomain - wb: [644] 13 bytes
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsdomain to 0:0
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_growpart.pyc'>) with frequency always
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
Feb 22 18:43:48 cloud-init[3058]: helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f7199414550>)
Feb 22 18:43:48 cloud-init[3058]: cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'ignore_growroot_disabled': False, 'mode': 'auto', 'devices': ['/']}
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /proc/3058/mountinfo (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 2532 bytes from /proc/3058/mountinfo
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 1299 bytes from /proc/self/status
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 212 bytes from /etc/os-release
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /sys/class/block/xvda1/partition (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 2 bytes from /sys/class/block/xvda1/partition
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /sys/devices/vbd-51712/block/xvda/dev (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 6 bytes from /sys/devices/vbd-51712/block/xvda/dev
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: resize_devices took 0.040 seconds
Feb 22 18:43:48 cloud-init[3058]: cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/xvda, 1)
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_resizefs.pyc'>) with frequency always
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
Feb 22 18:43:48 cloud-init[3058]: helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f7199414b10>)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /proc/3058/mountinfo (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 2532 bytes from /proc/3058/mountinfo
Feb 22 18:43:48 cloud-init[3058]: cc_resizefs.py[DEBUG]: resize_info: dev=/dev/xvda1 mnt_point=/ path=/
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 1299 bytes from /proc/self/status
Feb 22 18:43:48 cloud-init[3058]: cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Forked child 3189 who will run callback log_time
Feb 22 18:43:48 cloud-init[3058]: cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Running module set-hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_set_hostname.pyc'>) with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/config-set-hostname: running config-set-hostname with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_set_hostname - wb: [644] 20 bytes
Feb 22 18:43:48 cloud-init[3058]: helpers.py[DEBUG]: Running config-set-hostname using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_set_hostname'>)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 77 bytes from /var/lib/cloud/data/set-hostname
Feb 22 18:43:48 cloud-init[3058]: cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/config-set-hostname: SUCCESS: config-set-hostname ran successfully
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Running module update-hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_update_hostname.pyc'>) with frequency always
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/config-update-hostname: running config-update-hostname with frequency always
Feb 22 18:43:48 cloud-init[3058]: helpers.py[DEBUG]: Running config-update-hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f719936b810>)
Feb 22 18:43:48 cloud-init[3058]: cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-92-21.ec2.internal (ip-172-31-92-21)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3189]: util.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-92-21.ec2.internal in 1 files
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 28 bytes
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/config-update-hostname: SUCCESS: config-update-hostname ran successfully
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Running module update-etc-hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_update_etc_hosts.pyc'>) with frequency always
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/config-update-etc-hosts: running config-update-etc-hosts with frequency always
Feb 22 18:43:48 cloud-init[3058]: helpers.py[DEBUG]: Running config-update-etc-hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f719936b8d0>)
Feb 22 18:43:48 cloud-init[3058]: cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update-etc-hosts
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/config-update-etc-hosts: SUCCESS: config-update-etc-hosts ran successfully
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_rsyslog.pyc'>) with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_rsyslog - wb: [644] 20 bytes
Feb 22 18:43:48 cloud-init[3058]: helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_rsyslog'>)
Feb 22 18:43:48 cloud-init[3058]: cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_users_groups.pyc'>) with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_users_groups - wb: [644] 20 bytes
Feb 22 18:43:48 cloud-init[3058]: helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_users_groups'>)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 212 bytes from /etc/os-release
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
Feb 22 18:43:48 cloud-init[3058]: __init__.py[DEBUG]: Adding user ec2-user
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['useradd', 'ec2-user', '--comment', 'EC2 Default User', '--groups', 'adm,systemd-journal,wheel', '--shell', '/bin/bash', '-m']
Feb 22 18:43:48 cloud-init[3189]: util.py[DEBUG]: backgrounded Resizing took 0.012 seconds
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 3938 bytes from /etc/sudoers
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - wb: [440] 139 bytes
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_ssh.pyc'>) with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_ssh - wb: [644] 20 bytes
Feb 22 18:43:48 cloud-init[3058]: helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_ssh'>)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 3975 bytes from /etc/ssh/sshd_config
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 388 bytes
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Changing the ownership of /root/.ssh to 0:0
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 3975 bytes from /etc/ssh/sshd_config
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 545 bytes
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
Feb 22 18:43:48 cloud-init[3058]: stages.py[DEBUG]: Running module resolv-conf (<module 'cloudinit.config.cc_resolv_conf' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_resolv_conf.pyc'>) with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: start: init-network/config-resolv-conf: running config-resolv-conf with frequency once-per-instance
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_resolv_conf - wb: [644] 20 bytes
Feb 22 18:43:48 cloud-init[3058]: helpers.py[DEBUG]: Running config-resolv-conf using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_resolv_conf'>)
Feb 22 18:43:48 cloud-init[3058]: cc_resolv_conf.py[DEBUG]: Skipping module named resolv-conf, no 'manage_resolv_conf' key in configuration
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network/config-resolv-conf: SUCCESS: config-resolv-conf ran successfully
Feb 22 18:43:48 cloud-init[3058]: main.py[DEBUG]: Ran 13 modules with 0 failures
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: Read 10 bytes from /proc/uptime
Feb 22 18:43:48 cloud-init[3058]: util.py[DEBUG]: cloud-init mode 'init' took 0.913 seconds (0.92)
Feb 22 18:43:48 cloud-init[3058]: handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Cloud-init v. 18.2-72.amzn2.0.6 running 'modules:config' at Fri, 22 Feb 2019 18:43:49 +0000. Up 9.48 seconds.
Feb 22 18:43:49 cloud-init[3203]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Feb 22 18:43:49 cloud-init[3203]: stages.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_disk_setup.pyc'>) with frequency once-per-instance
Feb 22 18:43:49 cloud-init[3203]: handlers.py[DEBUG]: start: modules-config/config-disk_setup: running config-disk_setup with frequency once-per-instance
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_disk_setup - wb: [644] 20 bytes
Feb 22 18:43:49 cloud-init[3203]: helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_disk_setup'>)
Feb 22 18:43:49 cloud-init[3203]: handlers.py[DEBUG]: finish: modules-config/config-disk_setup: SUCCESS: config-disk_setup ran successfully
Feb 22 18:43:49 cloud-init[3203]: stages.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_mounts.pyc'>) with frequency once-per-instance
Feb 22 18:43:49 cloud-init[3203]: handlers.py[DEBUG]: start: modules-config/config-mounts: running config-mounts with frequency once-per-instance
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_mounts - wb: [644] 20 bytes
Feb 22 18:43:49 cloud-init[3203]: helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_mounts'>)
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: mounts configuration is [['ephemeral0', '/media/ephemeral0'], ['swap', 'none', 'swap', 'sw', '0', '0']]
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Read 91 bytes from /etc/fstab
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
Feb 22 18:43:49 cloud-init[3203]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: changed ephemeral0 => None
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount ephemeral0
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
Feb 22 18:43:49 cloud-init[3203]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: changed swap => None
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount swap
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
Feb 22 18:43:49 cloud-init[3203]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
Feb 22 18:43:49 cloud-init[3203]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: changed default device swap => None
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: Skipping nonexistent device named None
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: Skipping nonexistent device named None
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: no need to setup swap
Feb 22 18:43:49 cloud-init[3203]: cc_mounts.py[DEBUG]: No modifications to fstab needed
Feb 22 18:43:49 cloud-init[3203]: handlers.py[DEBUG]: finish: modules-config/config-mounts: SUCCESS: config-mounts ran successfully
Feb 22 18:43:49 cloud-init[3203]: stages.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_locale.pyc'>) with frequency once-per-instance
Feb 22 18:43:49 cloud-init[3203]: handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_locale - wb: [644] 20 bytes
Feb 22 18:43:49 cloud-init[3203]: helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_locale'>)
Feb 22 18:43:49 cloud-init[3203]: cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 97 bytes
Feb 22 18:43:49 cloud-init[3203]: handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
Feb 22 18:43:49 cloud-init[3203]: stages.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_set_passwords.pyc'>) with frequency once-per-instance
Feb 22 18:43:49 cloud-init[3203]: handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_set_passwords - wb: [644] 20 bytes
Feb 22 18:43:49 cloud-init[3203]: helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_set_passwords'>)
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Read 3975 bytes from /etc/ssh/sshd_config
Feb 22 18:43:49 cloud-init[3203]: ssh_util.py[DEBUG]: line 63: option PasswordAuthentication updated yes -> no
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Writing to /etc/ssh/sshd_config - wb: [600] 3974 bytes
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Running command ['service', 'sshd', 'restart'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:49 cloud-init[3203]: cc_set_passwords.py[DEBUG]: Restarted the ssh daemon.
Feb 22 18:43:49 cloud-init[3203]: handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
Feb 22 18:43:49 cloud-init[3203]: stages.py[DEBUG]: Running module yum-configure (<module 'cloudinit.config.cc_yum_configure' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_yum_configure.pyc'>) with frequency once-per-instance
Feb 22 18:43:49 cloud-init[3203]: handlers.py[DEBUG]: start: modules-config/config-yum-configure: running config-yum-configure with frequency once-per-instance
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_yum_configure - wb: [644] 20 bytes
Feb 22 18:43:49 cloud-init[3203]: helpers.py[DEBUG]: Running config-yum-configure using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_yum_configure'>)
Feb 22 18:43:49 cloud-init[3203]: cc_yum_configure.py[DEBUG]: Generating default repo files
Feb 22 18:43:49 cloud-init[3203]: __init__.py[DEBUG]: filtered distro mirror info: {}
Feb 22 18:43:49 cloud-init[3203]: cc_yum_configure.py[DEBUG]: mirror_info: {}
Feb 22 18:43:49 cloud-init[3203]: cc_yum_configure.py[DEBUG]: No mirror info found; ignoring.
Feb 22 18:43:49 cloud-init[3203]: cc_yum_configure.py[INFO]: No releasever provided, leaving yum.conf unchanged.
Feb 22 18:43:49 cloud-init[3203]: handlers.py[DEBUG]: finish: modules-config/config-yum-configure: SUCCESS: config-yum-configure ran successfully
Feb 22 18:43:49 cloud-init[3203]: stages.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_yum_add_repo.pyc'>) with frequency once-per-instance
Feb 22 18:43:49 cloud-init[3203]: handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_yum_add_repo - wb: [644] 20 bytes
Feb 22 18:43:49 cloud-init[3203]: helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_yum_add_repo'>)
Feb 22 18:43:49 cloud-init[3203]: cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
Feb 22 18:43:49 cloud-init[3203]: handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
Feb 22 18:43:49 cloud-init[3203]: stages.py[DEBUG]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_package_update_upgrade_install.pyc'>) with frequency once-per-instance
Feb 22 18:43:49 cloud-init[3203]: handlers.py[DEBUG]: start: modules-config/config-package-update-upgrade-install: running config-package-update-upgrade-install with frequency once-per-instance
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_package_update_upgrade_install - wb: [644] 20 bytes
Feb 22 18:43:49 cloud-init[3203]: helpers.py[DEBUG]: Running config-package-update-upgrade-install using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_package_update_upgrade_install'>)
Feb 22 18:43:49 cloud-init[3203]: amazon.py[DEBUG]: Upgrade level: security
Feb 22 18:43:49 cloud-init[3203]: rhel.py[DEBUG]: Using YUM for package management
Feb 22 18:43:49 cloud-init[3203]: util.py[DEBUG]: Running command ['yum', '-t', '-y', '--exclude=kernel', '--exclude=nvidia*', '--exclude=cuda*', '--security', '--sec-severity=critical', '--sec-severity=important', 'upgrade'] with allowed return codes [0] (shell=False, capture=False)
Feb 22 18:43:59 cloud-init[3203]: handlers.py[DEBUG]: finish: modules-config/config-package-update-upgrade-install: SUCCESS: config-package-update-upgrade-install ran successfully
Feb 22 18:43:59 cloud-init[3203]: stages.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_timezone.pyc'>) with frequency once-per-instance
Feb 22 18:43:59 cloud-init[3203]: handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
Feb 22 18:43:59 cloud-init[3203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_timezone - wb: [644] 20 bytes
Feb 22 18:43:59 cloud-init[3203]: helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_timezone'>)
Feb 22 18:43:59 cloud-init[3203]: cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
Feb 22 18:43:59 cloud-init[3203]: handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
Feb 22 18:43:59 cloud-init[3203]: stages.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_disable_ec2_metadata.pyc'>) with frequency always
Feb 22 18:43:59 cloud-init[3203]: handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
Feb 22 18:43:59 cloud-init[3203]: helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f7a71036190>)
Feb 22 18:43:59 cloud-init[3203]: cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
Feb 22 18:43:59 cloud-init[3203]: handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
Feb 22 18:43:59 cloud-init[3203]: stages.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_runcmd.pyc'>) with frequency once-per-instance
Feb 22 18:43:59 cloud-init[3203]: handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
Feb 22 18:43:59 cloud-init[3203]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_runcmd - wb: [644] 20 bytes
Feb 22 18:43:59 cloud-init[3203]: helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_runcmd'>)
Feb 22 18:43:59 cloud-init[3203]: cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
Feb 22 18:43:59 cloud-init[3203]: handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
Feb 22 18:43:59 cloud-init[3203]: main.py[DEBUG]: Ran 10 modules with 0 failures
Feb 22 18:43:59 cloud-init[3203]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Feb 22 18:43:59 cloud-init[3203]: util.py[DEBUG]: Read 11 bytes from /proc/uptime
Feb 22 18:43:59 cloud-init[3203]: util.py[DEBUG]: cloud-init mode 'modules' took 9.424 seconds (9.42)
Feb 22 18:43:59 cloud-init[3203]: handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Cloud-init v. 18.2-72.amzn2.0.6 running 'modules:final' at Fri, 22 Feb 2019 18:43:59 +0000. Up 19.46 seconds.
Feb 22 18:43:59 cloud-init[3408]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Feb 22 18:43:59 cloud-init[3408]: stages.py[DEBUG]: Running module scripts-per-once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_per_once.pyc'>) with frequency once
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: start: modules-final/config-scripts-per-once: running config-scripts-per-once with frequency once
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 20 bytes
Feb 22 18:43:59 cloud-init[3408]: helpers.py[DEBUG]: Running config-scripts-per-once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: finish: modules-final/config-scripts-per-once: SUCCESS: config-scripts-per-once ran successfully
Feb 22 18:43:59 cloud-init[3408]: stages.py[DEBUG]: Running module scripts-per-boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_per_boot.pyc'>) with frequency always
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: start: modules-final/config-scripts-per-boot: running config-scripts-per-boot with frequency always
Feb 22 18:43:59 cloud-init[3408]: helpers.py[DEBUG]: Running config-scripts-per-boot using lock (<cloudinit.helpers.DummyLock object at 0x7f5c822ba250>)
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: finish: modules-final/config-scripts-per-boot: SUCCESS: config-scripts-per-boot ran successfully
Feb 22 18:43:59 cloud-init[3408]: stages.py[DEBUG]: Running module scripts-per-instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_per_instance.pyc'>) with frequency once-per-instance
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: start: modules-final/config-scripts-per-instance: running config-scripts-per-instance with frequency once-per-instance
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_scripts_per_instance - wb: [644] 20 bytes
Feb 22 18:43:59 cloud-init[3408]: helpers.py[DEBUG]: Running config-scripts-per-instance using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_scripts_per_instance'>)
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: finish: modules-final/config-scripts-per-instance: SUCCESS: config-scripts-per-instance ran successfully
Feb 22 18:43:59 cloud-init[3408]: stages.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) with frequency once-per-instance
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_scripts_user - wb: [644] 20 bytes
Feb 22 18:43:59 cloud-init[3408]: helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_scripts_user'>)
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
Feb 22 18:43:59 cloud-init[3408]: stages.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_ssh_authkey_fingerprints.pyc'>) with frequency once-per-instance
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_ssh_authkey_fingerprints - wb: [644] 20 bytes
Feb 22 18:43:59 cloud-init[3408]: helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_ssh_authkey_fingerprints'>)
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Read 3974 bytes from /etc/ssh/sshd_config
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Read 388 bytes from /home/ec2-user/.ssh/authorized_keys
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints ran successfully
Feb 22 18:43:59 cloud-init[3408]: stages.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_keys_to_console.pyc'>) with frequency once-per-instance
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_keys_to_console - wb: [644] 20 bytes
Feb 22 18:43:59 cloud-init[3408]: helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_keys_to_console'>)
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Running command ['/usr/libexec/cloud-init/write-ssh-key-fingerprints', '', 'ssh-dss'] with allowed return codes [0] (shell=False, capture=True)
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console ran successfully
Feb 22 18:43:59 cloud-init[3408]: stages.py[DEBUG]: Running module phone-home (<module 'cloudinit.config.cc_phone_home' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_phone_home.pyc'>) with frequency once-per-instance
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: start: modules-final/config-phone-home: running config-phone-home with frequency once-per-instance
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_phone_home - wb: [644] 20 bytes
Feb 22 18:43:59 cloud-init[3408]: helpers.py[DEBUG]: Running config-phone-home using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_phone_home'>)
Feb 22 18:43:59 cloud-init[3408]: cc_phone_home.py[DEBUG]: Skipping module named phone-home, no 'phone_home' configuration found
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: finish: modules-final/config-phone-home: SUCCESS: config-phone-home ran successfully
Feb 22 18:43:59 cloud-init[3408]: stages.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_final_message.pyc'>) with frequency always
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
Feb 22 18:43:59 cloud-init[3408]: helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7f5c822ba950>)
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Read 11 bytes from /proc/uptime
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Cloud-init v. 18.2-72.amzn2.0.6 finished at Fri, 22 Feb 2019 18:43:59 +0000. Datasource DataSourceEc2.  Up 19.83 seconds
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 63 bytes
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
Feb 22 18:43:59 cloud-init[3408]: stages.py[DEBUG]: Running module power-state-change (<module 'cloudinit.config.cc_power_state_change' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_power_state_change.pyc'>) with frequency once-per-instance
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: start: modules-final/config-power-state-change: running config-power-state-change with frequency once-per-instance
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_power_state_change - wb: [644] 20 bytes
Feb 22 18:43:59 cloud-init[3408]: helpers.py[DEBUG]: Running config-power-state-change using lock (<FileLock using file '/var/lib/cloud/instances/i-01810bd6547e312e1/sem/config_power_state_change'>)
Feb 22 18:43:59 cloud-init[3408]: cc_power_state_change.py[DEBUG]: no power_state provided. doing nothing
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: finish: modules-final/config-power-state-change: SUCCESS: config-power-state-change ran successfully
Feb 22 18:43:59 cloud-init[3408]: main.py[DEBUG]: Ran 9 modules with 0 failures
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: Read 11 bytes from /proc/uptime
Feb 22 18:43:59 cloud-init[3408]: util.py[DEBUG]: cloud-init mode 'modules' took 0.393 seconds (0.39)
Feb 22 18:43:59 cloud-init[3408]: handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
